# this file uses the images from: ./images
version: "3"
services:
  pgsql-1:
    # postgresql://postgres:password@localhost:5432/database_1
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - "./pgdata/1:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_1
    restart: always

  pgsql-2:
    # postgresql://postgres:password@localhost:5433/database_2
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - "./pgdata/2:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_2
    restart: always

  zookeeper:
    container_name: zookeeper
    build: images/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    container_name: kafka
    build: images/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  schema-registry:
    container_name: schema-registry
    image: confluent/schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zookeeper
      - kafka
