version: "3"
services:
  pgsql-1:
    # postgresql://postgres:password@localhost:5432/database_1
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - "./pgdata/1:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_1
    restart: always

  pgsql-2:
    # postgresql://postgres:password@localhost:5433/database_2
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - "./pgdata/2:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_2
    restart: always

  zookeeper:
    build: images/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    build: images/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
